// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: bbriumexzwirqebnotfo

class SupabaseConfig {
  static const String supabaseUrl = 'https://bbriumexzwirqebnotfo.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicml1bWV4endpcnFlYm5vdGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3Mzk0MzYsImV4cCI6MjA4MDMxNTQzNn0.tU21MNJ3KYdjPVO2ej_8UltNa9xcFhp5Nyl3kbfdnLE';
}
